In [12]:
import pandas as pd
from pathlib import Path
import glob

In [33]:
data_path = "/Users/meeratrivedi/Downloads/STAT 390/data"

**Data Import Code**

In [34]:
folder = Path(data_path)
files = sorted(list(folder.glob("*.csv")) + list(folder.glob("*.xlsx")))
df_main = pd.DataFrame(columns=['Contact Session ID', 'EP Name', 'Flow Name', 'Activity Name', 'Activity Start Timestamp', 
                                'Queue Name', 'Agent Name', 'Termination Reason'])
df_main

Empty DataFrame
Columns: [Contact Session ID, EP Name, Flow Name, Activity Name, Activity Start Timestamp, Queue Name, Agent Name, Termination Reason]
Index: []

In [35]:
i=0
for f in files:
    i = i + 1
    if f.suffix.lower() == ".csv":
        df = pd.read_csv(f, header=2, dtype=str, engine="python", skip_blank_lines=False)
    else:  # .xlsx
        df = pd.read_excel(f, sheet_name=0, header=2, dtype=str)
    df_main = pd.concat([df_main, df], ignore_index=True)
    print(i, f.stem, df.shape)

1 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 3-16 to 3-22-25 (45326, 8)
2 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 3-30 to 4-5-25 (45072, 8)

In [36]:
df_main["Activity Start Timestamp"] = pd.to_datetime(df_main["Activity Start Timestamp"], errors="coerce")
# Creating a new column 'hour' as it will be useful to visualize peak calling hours
df_main["hour"] = df_main["Activity Start Timestamp"].dt.hour
df_main["weekday"] = df_main["Activity Start Timestamp"].dt.day_name()

/var/folders/vr/tdmh9w694nx9v20sfh47x4tr0000gn/T/ipykernel_63665/3439861526.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_main["Activity Start Timestamp"] = pd.to_datetime(df_main["Activity Start Timestamp"], errors="coerce")

In [38]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90398 entries, 0 to 90397
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Contact Session ID        90398 non-null  object
 1   EP Name                   68092 non-null  object
 2   Flow Name                 24796 non-null  object
 3   Activity Name             40484 non-null  object
 4   Activity Start Timestamp  90398 non-null  datetime64[ns]
 5   Queue Name                12355 non-null  object
 6   Agent Name                9002 non-null   object
 7   Termination Reason        7605 non-null   object
 8   hour                      90398 non-null  int32
 9   weekday                   90398 non-null  object
dtypes: datetime64[ns](1), int32(1), object(8)
memory usage: 6.6+ MB

In [39]:
df_main.head(10)

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour,weekday
0,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,2025-03-16 00:40:10,NaN,NaN,NaN,0,Sunday
1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,NaN,LACMain,NaN,2025-03-16 00:40:10,NaN,NaN,NaN,0,Sunday
2,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025-03-16 00:40:10,NaN,NaN,NaN,0,Sunday
3,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,LACMain,NaN,2025-03-16 00:40:10,NaN,NaN,NaN,0,Sunday
4,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,2025-03-16 00:40:12,NaN,NaN,Customer Left,0,Sunday
5,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:16,Consumer SP,NaN,Queue Timeout,2,Sunday
6,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:16,Consumer SP,NaN,Customer Left,2,Sunday
7,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,CallbackRetry,2025-03-16 02:15:26,NaN,NaN,NaN,2,Sunday
8,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:26,Consumer SP,NaN,NaN,2,Sunday
9,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:26,Consumer SP,NaN,Customer Left,2,Sunday

In [41]:
##Customer Left

customer_left = df_main[df_main['Termination Reason'] == 'Customer Left']

customer_left.head(10)

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour,weekday
4,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,2025-03-16 00:40:12,NaN,NaN,Customer Left,0,Sunday
6,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:16,Consumer SP,NaN,Customer Left,2,Sunday
9,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:26,Consumer SP,NaN,Customer Left,2,Sunday
10,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,NaN,2025-03-16 02:15:26,Consumer SP,NaN,Customer Left,2,Sunday
24,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,2025-03-16 02:42:18,Staff Directory English Transfer,CBT Agent,Customer Left,2,Sunday
36,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,NaN,NaN,2025-03-16 07:51:33,NaN,NaN,Customer Left,7,Sunday
47,2cf62d7e-60f7-4ea9-86c4-24583bd96baa,Main Number Telephony EP,LACMain,NaN,2025-03-16 08:21:15,NaN,NaN,Customer Left,8,Sunday
48,2cf62d7e-60f7-4ea9-86c4-24583bd96baa,Main Number Telephony EP,NaN,NaN,2025-03-16 08:21:15,NaN,NaN,Customer Left,8,Sunday
54,c12bfc6c-1bf8-4203-a1cf-df4106cc252f,Farmworker Main Number Telephony EP,NaN,NaN,2025-03-16 08:30:32,NaN,NaN,Customer Left,8,Sunday
60,133abc79-dcd0-4331-8305-6a8ec3fcf97f,Farmworker Main Number Telephony EP,NaN,NaN,2025-03-16 08:55:12,NaN,NaN,Customer Left,8,Sunday

In [67]:
#Inner join
calls_customer_left = df_main[df_main["Contact Session ID"].isin(customer_left["Contact Session ID"])].copy()

#Give each session ID an ID number in order of appearance
calls_customer_left["Call ID"] = calls_customer_left["Contact Session ID"].map(
    {id_: i+1 for i, id_ in enumerate(calls_customer_left["Contact Session ID"].unique())}
)
#Separate out the time
calls_customer_left["Time"] = calls_customer_left["Activity Start Timestamp"].dt.strftime("%I:%M:%S %p")
calls_customer_left["Time"] = pd.to_datetime(calls_customer_left["Time"], errors="coerce")

#Calculate Time Difference between rows 
calls_customer_left["Time Difference"] = (
    calls_customer_left.groupby("Contact Session ID")["Time"]
    .diff()
    .dt.total_seconds()  
)

calls_customer_left = calls_customer_left[
    [
        'Call ID',
        'Contact Session ID',
        'EP Name',
        'Flow Name',
        'Activity Name',
        'Queue Name',
        'Termination Reason',
        'Activity Start Timestamp',
        'Time',
        'Time Difference', 
        'weekday', 
    ]
]

calls_customer_left.head(5)

/var/folders/vr/tdmh9w694nx9v20sfh47x4tr0000gn/T/ipykernel_63665/3599249880.py:10: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  calls_customer_left["Time"] = pd.to_datetime(calls_customer_left["Time"], errors="coerce")

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time,Time Difference,weekday
0,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 00:40:10,2025-10-20 00:40:10,NaN,Sunday
1,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,NaN,LACMain,NaN,NaN,NaN,2025-03-16 00:40:10,2025-10-20 00:40:10,0.0,Sunday
2,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 00:40:10,2025-10-20 00:40:10,0.0,Sunday
3,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,LACMain,NaN,NaN,NaN,2025-03-16 00:40:10,2025-10-20 00:40:10,0.0,Sunday
4,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,NaN,Customer Left,2025-03-16 00:40:12,2025-10-20 00:40:12,2.0,Sunday