In [36]:
import pandas as pd
from pathlib import Path
import glob

In [37]:
data_path = "/Users/meeratrivedi/Downloads/STAT 390/data"

## Data Import Code

In [38]:
folder = Path(data_path)
files = sorted(list(folder.glob("*.csv")) + list(folder.glob("*.xlsx")))
df_main = pd.DataFrame(columns=['Contact Session ID', 'EP Name', 'Flow Name', 'Activity Name', 'Activity Start Timestamp', 
                                'Queue Name', 'Agent Name', 'Termination Reason'])
df_main

Empty DataFrame
Columns: [Contact Session ID, EP Name, Flow Name, Activity Name, Activity Start Timestamp, Queue Name, Agent Name, Termination Reason]
Index: []

In [39]:
i=0
for f in files:
    i = i + 1
    if f.suffix.lower() == ".csv":
        df = pd.read_csv(f, header=2, dtype=str, engine="python", skip_blank_lines=False)
    else:  # .xlsx
        df = pd.read_excel(f, sheet_name=0, header=2, dtype=str)
    df_main = pd.concat([df_main, df], ignore_index=True)
    print(i, f.stem, df.shape)

1 CAR - EP, Flow, Activity, Queue, & Agent Names (01-12-25 - 01-18-25) (52010, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

2 CAR - EP, Flow, Activity, Queue, & Agent Names (01-19-25 - 02-01-25) (95495, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

3 CAR - EP, Flow, Activity, Queue, & Agent Names (02-02-25 - 02-15-25) (90056, 7)
4 CAR - EP, Flow, Activity, Queue, & Agent Names (02-16-25 - 03-01-25) (88186, 7)
5 CAR - EP, Flow, Activity, Queue, & Agent Names (03-02-25 - 03-15-25) (86377, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

6 CAR - EP, Flow, Activity, Queue, & Agent Names (04-07-24 - 04-20-24) (88766, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

7 CAR - EP, Flow, Activity, Queue, & Agent Names (04-21-24 - 05-04-24) (89643, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

8 CAR - EP, Flow, Activity, Queue, & Agent Names (05-05-24 - 05-18-24) (82575, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

9 CAR - EP, Flow, Activity, Queue, & Agent Names (05-19-24 - 06-01-24) (71103, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

10 CAR - EP, Flow, Activity, Queue, & Agent Names (06-02-24 - 06-15-24) (84354, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

11 CAR - EP, Flow, Activity, Queue, & Agent Names (06-16-24 - 06-29-24) (82124, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

12 CAR - EP, Flow, Activity, Queue, & Agent Names (06-30-24 - 07-13-24) (79752, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

13 CAR - EP, Flow, Activity, Queue, & Agent Names (07-14-24 - 07-27-24) (85110, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

14 CAR - EP, Flow, Activity, Queue, & Agent Names (07-28-24 - 08-10-24) (84627, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

15 CAR - EP, Flow, Activity, Queue, & Agent Names (08-11-24 - 08-24-24) (91622, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

16 CAR - EP, Flow, Activity, Queue, & Agent Names (08-24-24 - 09-07-24) (90040, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

17 CAR - EP, Flow, Activity, Queue, & Agent Names (09-08-24 - 09-21-24) (96581, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

18 CAR - EP, Flow, Activity, Queue, & Agent Names (09-22-24 - 10-05-24) (89446, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

19 CAR - EP, Flow, Activity, Queue, & Agent Names (10-06-24 - 10-19-24) (81700, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

20 CAR - EP, Flow, Activity, Queue, & Agent Names (10-20-24 - 11-02-24) (88430, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

21 CAR - EP, Flow, Activity, Queue, & Agent Names (11-03-24 - 11-16-24) (81614, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

22 CAR - EP, Flow, Activity, Queue, & Agent Names (11-17-24 - 11-30-24) (66216, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

23 CAR - EP, Flow, Activity, Queue, & Agent Names (12-01-24 - 12-14-24) (92220, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

24 CAR - EP, Flow, Activity, Queue, & Agent Names (12-15-24 - 12-28-24) (62143, 7)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

25 CAR - EP, Flow, Activity, Queue, & Agent Names (12-29-24 - 01-11-25) (75356, 7)
26 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 3-16 to 3-22-25 (45326, 8)
27 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 3-30 to 4-5-25 (45072, 8)
28 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-13 to 4-19-25 (41088, 8)
29 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-20 to 4-26-25 (46686, 8)
30 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-27 to 5-3-25 (44169, 8)
31 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-6 to 4-12-25 (46630, 8)
32 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-11 to 5-17-25 (43268, 8)
33 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-18 to 5-24-25 (45104, 8)
34 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-25 to 5-31-25 (36851, 8)
35 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-4 to 5-10-25 (43955, 8)
36 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-1 to 6-7-25 (44523, 8)
37 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-15 to 6-21-25 (37234, 8)
38 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-22 to 6-28-25 (45394, 8)
39 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-29 to 7-5-25 (38300, 8)
40 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-8 to 6-14-25 (46728, 8)
41 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-13 to 7-19-25 (45706, 8)
42 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-20 to 7-26-25 (45328, 8)
43 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-28 ro 8-2-25 (46237, 8)
44 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-6 to 7-12-25 (48707, 8)
45 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-10 to 8-16-25 (44095, 8)
46 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-17 to 8-23-25 (47062, 8)
47 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-24 to 8-30-25 (45113, 8)
48 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-3 to 8-9-25 (44706, 8)
49 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-31 to 9-6-25 (36177, 8)
50 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 9-14 to 9-20-25 (45958, 8)
51 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 9-21 to 9-30-25 (60381, 8)
52 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 9-7 to 9-13-25 (45304, 8)
53 CAR - EP, Flow, Activity, Queue, &amp; Agent Names3-23 to 3-29-25 (47978, 8)

In [40]:
df_main["Activity Start Timestamp"] = pd.to_datetime(df_main["Activity Start Timestamp"], errors="coerce")
# Creating a new column 'hour' as it will be useful to visualize peak calling hours
df_main["hour"] = df_main["Activity Start Timestamp"].dt.hour
df_main["weekday"] = df_main["Activity Start Timestamp"].dt.day_name()

In [41]:
df_main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3328626 entries, 0 to 3328625
Data columns (total 10 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Contact Session ID        object
 1   EP Name                   object
 2   Flow Name                 object
 3   Activity Name             object
 4   Activity Start Timestamp  datetime64[ns]
 5   Queue Name                object
 6   Agent Name                object
 7   Termination Reason        object
 8   hour                      int32
 9   weekday                   object
dtypes: datetime64[ns](1), int32(1), object(8)
memory usage: 241.3+ MB

In [42]:
df_main['Contact Session ID'].nunique()

248442

In [43]:
#WRITE OUT KRISH CLEANING FILE TO USE IN R
#!pip install openpyxl


df_main.to_csv("/Users/meeratrivedi/Downloads/STAT 390/krish_cleaning_full.csv", index=False)

In [44]:
df_main.head(10)

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour,weekday
0,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,NaN,2025-01-14 12:39:32,NaN,NaN,NaN,12,Tuesday
1,001a3748-8d50-4550-8461-33547983deb0,NaN,LACMain,NaN,2025-01-14 12:39:32,NaN,NaN,NaN,12,Tuesday
2,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025-01-14 12:39:32,NaN,NaN,NaN,12,Tuesday
3,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,LACMain,NaN,2025-01-14 12:39:32,NaN,NaN,NaN,12,Tuesday
4,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,MainMenu,2025-01-14 12:39:45,NaN,NaN,NaN,12,Tuesday
5,001a3748-8d50-4550-8461-33547983deb0,NaN,PreLegalMenuSeniorsMenu,NaN,2025-01-14 12:40:09,NaN,NaN,NaN,12,Tuesday
6,001a3748-8d50-4550-8461-33547983deb0,Pre-Legal Menu Seniors Menu Telephony EP,NaN,SeniorsMenu,2025-01-14 12:40:09,NaN,NaN,NaN,12,Tuesday
7,001a3748-8d50-4550-8461-33547983deb0,NaN,LegalMenu,NaN,2025-01-14 12:40:18,NaN,NaN,NaN,12,Tuesday
8,001a3748-8d50-4550-8461-33547983deb0,Legal Menu Telephony EP,NaN,LegalMenu1,2025-01-14 12:40:18,NaN,NaN,NaN,12,Tuesday
9,001a3748-8d50-4550-8461-33547983deb0,Legal Menu Telephony EP,NaN,LegalMenu2,2025-01-14 12:40:54,NaN,NaN,NaN,12,Tuesday

## Data Cleaning

In [41]:
##Customer Left

customer_left = df_main[df_main['Termination Reason'] == 'Customer Left']

customer_left.head(10)

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason,hour,weekday
4,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,2025-03-16 00:40:12,NaN,NaN,Customer Left,0,Sunday
6,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:16,Consumer SP,NaN,Customer Left,2,Sunday
9,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,2025-03-16 02:15:26,Consumer SP,NaN,Customer Left,2,Sunday
10,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,NaN,2025-03-16 02:15:26,Consumer SP,NaN,Customer Left,2,Sunday
24,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,2025-03-16 02:42:18,Staff Directory English Transfer,CBT Agent,Customer Left,2,Sunday
36,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,NaN,NaN,2025-03-16 07:51:33,NaN,NaN,Customer Left,7,Sunday
47,2cf62d7e-60f7-4ea9-86c4-24583bd96baa,Main Number Telephony EP,LACMain,NaN,2025-03-16 08:21:15,NaN,NaN,Customer Left,8,Sunday
48,2cf62d7e-60f7-4ea9-86c4-24583bd96baa,Main Number Telephony EP,NaN,NaN,2025-03-16 08:21:15,NaN,NaN,Customer Left,8,Sunday
54,c12bfc6c-1bf8-4203-a1cf-df4106cc252f,Farmworker Main Number Telephony EP,NaN,NaN,2025-03-16 08:30:32,NaN,NaN,Customer Left,8,Sunday
60,133abc79-dcd0-4331-8305-6a8ec3fcf97f,Farmworker Main Number Telephony EP,NaN,NaN,2025-03-16 08:55:12,NaN,NaN,Customer Left,8,Sunday

In [121]:
#Inner join
calls_customer_left = df_main[df_main["Contact Session ID"].isin(customer_left["Contact Session ID"])].copy()

#Give each session ID an ID number in order of appearance
calls_customer_left["Call ID"] = (
    (calls_customer_left["Contact Session ID"] != calls_customer_left["Contact Session ID"].shift())
    .cumsum()
)


#Calculate Time Difference between rows 
calls_customer_left["Time Difference"] = (
    calls_customer_left.groupby("Contact Session ID")["Activity Start Timestamp"]
    .diff()
    .dt.total_seconds()  
)

calls_customer_left = calls_customer_left[
    [
        'Call ID',
        'Contact Session ID',
        'EP Name',
        'Flow Name',
        'Activity Name',
        'Queue Name',
        'Termination Reason',
        'Activity Start Timestamp',
        'Time Difference', #seconds
        'weekday', 
    ]
]

calls_customer_left.head(5)

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
0,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 00:40:10,NaN,Sunday
1,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,NaN,LACMain,NaN,NaN,NaN,2025-03-16 00:40:10,0.0,Sunday
2,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 00:40:10,0.0,Sunday
3,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,LACMain,NaN,NaN,NaN,2025-03-16 00:40:10,0.0,Sunday
4,1,ced63a4a-89f4-4e11-94b3-447a01cd34cb,Main Number Telephony EP,NaN,NaN,NaN,Customer Left,2025-03-16 00:40:12,2.0,Sunday

## Example 1: Customer Left after long wait time

#### On FarmworkerMainMenu and left after 24 minutes.

In [126]:
calls_customer_left[calls_customer_left["Call ID"] == 4]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
31,4,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 07:27:28,NaN,Sunday
32,4,6364de29-c942-4e6f-95fe-4a63ee631450,NaN,FarmworkerMain,NaN,NaN,NaN,2025-03-16 07:27:28,0.0,Sunday
33,4,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 07:27:28,0.0,Sunday
34,4,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,FarmworkerMain,NaN,NaN,NaN,2025-03-16 07:27:28,0.0,Sunday
35,4,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,NaN,FarmworkerMainMenu,NaN,NaN,2025-03-16 07:27:36,8.0,Sunday
36,4,6364de29-c942-4e6f-95fe-4a63ee631450,Farmworker Main Number Telephony EP,NaN,NaN,NaN,Customer Left,2025-03-16 07:51:33,1437.0,Sunday

#### On FarmworkerMainMenu and left after 30 minutes.

In [129]:
calls_customer_left[calls_customer_left["Call ID"] == 14]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
87,14,b2a3d237-f14d-4b64-95a1-6121068748ff,Farmworker Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 10:58:22,NaN,Sunday
88,14,b2a3d237-f14d-4b64-95a1-6121068748ff,NaN,FarmworkerMain,NaN,NaN,NaN,2025-03-16 10:58:22,0.0,Sunday
89,14,b2a3d237-f14d-4b64-95a1-6121068748ff,Farmworker Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 10:58:22,0.0,Sunday
90,14,b2a3d237-f14d-4b64-95a1-6121068748ff,Farmworker Main Number Telephony EP,FarmworkerMain,NaN,NaN,NaN,2025-03-16 10:58:23,1.0,Sunday
91,14,b2a3d237-f14d-4b64-95a1-6121068748ff,Farmworker Main Number Telephony EP,NaN,FarmworkerMainMenu,NaN,NaN,2025-03-16 10:58:30,7.0,Sunday
92,14,b2a3d237-f14d-4b64-95a1-6121068748ff,Farmworker Main Number Telephony EP,NaN,NaN,NaN,Customer Left,2025-03-16 11:28:33,1803.0,Sunday

#### On FarmworkerMainMenu and left after 25 minutes.

In [132]:
calls_customer_left[calls_customer_left["Call ID"] == 25]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
142,25,7abc1633-1405-45f2-b69b-36520294a436,Farmworker Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 14:42:09,NaN,Sunday
143,25,7abc1633-1405-45f2-b69b-36520294a436,NaN,FarmworkerMain,NaN,NaN,NaN,2025-03-16 14:42:09,0.0,Sunday
144,25,7abc1633-1405-45f2-b69b-36520294a436,Farmworker Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 14:42:09,0.0,Sunday
145,25,7abc1633-1405-45f2-b69b-36520294a436,Farmworker Main Number Telephony EP,FarmworkerMain,NaN,NaN,NaN,2025-03-16 14:42:10,1.0,Sunday
146,25,7abc1633-1405-45f2-b69b-36520294a436,Farmworker Main Number Telephony EP,NaN,FarmworkerMainMenu,NaN,NaN,2025-03-16 14:42:17,7.0,Sunday
147,25,7abc1633-1405-45f2-b69b-36520294a436,Farmworker Main Number Telephony EP,NaN,NaN,NaN,Customer Left,2025-03-16 15:06:58,1481.0,Sunday

## Example 2: Customer Left during Courtesy Callback

#### Rows 10 and 255: Customer Left during Courtesy Callback Telephone EP.

In [136]:
calls_customer_left[
    (calls_customer_left["Call ID"] == 2)
]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
5,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,Queue Timeout,2025-03-16 02:15:16,NaN,Sunday
6,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,Customer Left,2025-03-16 02:15:16,0.0,Sunday
7,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,CallbackRetry,NaN,NaN,2025-03-16 02:15:26,10.0,Sunday
8,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,NaN,2025-03-16 02:15:26,0.0,Sunday
9,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,NaN,NaN,NaN,Consumer SP,Customer Left,2025-03-16 02:15:26,0.0,Sunday
10,2,7cb76bad-f177-4fdb-b0fd-681f9b2cceb0,Courtesy Callback Telephony EP,NaN,NaN,Consumer SP,Customer Left,2025-03-16 02:15:26,0.0,Sunday

## Example 3: Customer called during closed hours

#### This can get lumped in with intentionally abandoned calls since the customer called and left on their own.

Row 24: Customer left during closed hours, but also during a staff voicemail transfer? 
Why are there three rows for the transfer and 48 seconds of time when the transfer recording is only 5 seconds long?

In [160]:
calls_customer_left[calls_customer_left["Call ID"] == 3]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
11,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 02:39:46,NaN,Sunday
12,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,NaN,LACMain,NaN,NaN,NaN,2025-03-16 02:39:46,0.0,Sunday
13,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 02:39:46,0.0,Sunday
14,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Main Number Telephony EP,LACMain,NaN,NaN,NaN,2025-03-16 02:39:46,0.0,Sunday
15,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,NaN,ClosedHoursHolidaysMenu,NaN,NaN,NaN,2025-03-16 02:39:56,10.0,Sunday
16,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,ClosedMenu,NaN,NaN,2025-03-16 02:39:56,0.0,Sunday
17,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,AddressFaxHoursMenu,NaN,NaN,2025-03-16 02:40:48,52.0,Sunday
18,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,ClosedMenu,NaN,NaN,2025-03-16 02:41:21,33.0,Sunday
19,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,StaffDirectoryEnglishTransfer,NaN,NaN,2025-03-16 02:41:30,9.0,Sunday
20,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,NaN,NaN,NaN,Staff Directory English Transfer,NaN,2025-03-16 02:41:30,0.0,Sunday
21,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 02:41:30,0.0,Sunday
22,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,Staff Directory English Transfer,NaN,2025-03-16 02:41:30,0.0,Sunday
23,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,Staff Directory English Transfer,NaN,2025-03-16 02:41:30,0.0,Sunday
24,3,1b35074f-6d8b-4132-99a2-32ae83ea54cf,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,Staff Directory English Transfer,Customer Left,2025-03-16 02:42:18,48.0,Sunday

#### Seems like this person moved through all the menus and left. No voicemails

In [161]:
calls_customer_left[calls_customer_left["Call ID"] == 32]

,Call ID,Contact Session ID,EP Name,Flow Name,Activity Name,Queue Name,Termination Reason,Activity Start Timestamp,Time Difference,weekday
224,32,0d7b7955-b2d1-4383-ba0d-847648020b54,Main Number Telephony EP,NaN,NaN,NaN,NaN,2025-03-16 20:35:14,NaN,Sunday
225,32,0d7b7955-b2d1-4383-ba0d-847648020b54,NaN,LACMain,NaN,NaN,NaN,2025-03-16 20:35:14,0.0,Sunday
226,32,0d7b7955-b2d1-4383-ba0d-847648020b54,Main Number Telephony EP,NaN,LanguageSelectionMenu,NaN,NaN,2025-03-16 20:35:14,0.0,Sunday
227,32,0d7b7955-b2d1-4383-ba0d-847648020b54,Main Number Telephony EP,LACMain,NaN,NaN,NaN,2025-03-16 20:35:14,0.0,Sunday
228,32,0d7b7955-b2d1-4383-ba0d-847648020b54,NaN,ClosedHoursHolidaysMenu,NaN,NaN,NaN,2025-03-16 20:35:26,12.0,Sunday
229,32,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,ClosedMenu,NaN,NaN,2025-03-16 20:35:26,0.0,Sunday
230,32,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,AddressFaxHoursMenu,NaN,NaN,2025-03-16 20:36:13,47.0,Sunday
231,32,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,ClosedMenu,NaN,NaN,2025-03-16 20:36:46,33.0,Sunday
232,32,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,AddressFaxHoursMenu,NaN,NaN,2025-03-16 20:37:37,51.0,Sunday
233,32,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,ClosedMenu,NaN,NaN,2025-03-16 20:37:51,14.0,Sunday
234,32,0d7b7955-b2d1-4383-ba0d-847648020b54,Closed Hours-Holidays Menu Telephony EP,NaN,NaN,NaN,Customer Left,2025-03-16 20:37:51,0.0,Sunday