Author: Krish

In [1]:
# Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pandas.api.types import CategoricalDtype
from pathlib import Path
from functools import reduce

### User input required
Put the data path on your system in the cell below

In [2]:
# Enter data path
data_path = "C:\\Users\\akl0407\\OneDrive - Northwestern University\\Back up\\2025-26\\Spring 2025\\STAT390\\LegalAid\\Data\\All Calls by Month\\"

### User input ends

### Reading all filenames in the data folder

In [3]:
folder = Path(data_path)
files = sorted(list(folder.glob("*.csv")) + list(folder.glob("*.xlsx")))

### Reading first 5 rows of all data files
The code chunk below reads the first 5 rows of all data files. This is to check the columns that are present in all the data files.

In [5]:
i=0; df = []
for f in files:
    if f.suffix.lower() == ".csv":
        df.append(pd.read_csv(f, header=0, dtype=str, engine="python", skip_blank_lines=False, nrows = 5))
    else:  # .xlsx
        df.append(pd.read_excel(f, sheet_name=0, header=0, dtype=str, nrows = 5))
    #df_main = pd.concat([df_main, df], ignore_index=True)
    print(i, f.stem, df[i].shape)
    i = i + 1

0 April 2024 (5, 63)
1 April 2025 (5, 63)
2 August 2024 (5, 57)
3 August 2025 (5, 63)
4 December 2024 (5, 55)
5 February 2025 (5, 63)
6 January 2025 (5, 64)
7 July 2024 (5, 55)
8 July 2025 (5, 63)
9 June 2024 (5, 63)
10 June 2025 (5, 63)
11 March 2025 (5, 65)
12 May 2024 (5, 63)
13 May 2025 (5, 63)
14 November 2024 (5, 63)
15 October 2024 (5, 55)
16 September 2024 (5, 55)

The code chunk below identifies the columns missing in at least one DataFrame.

In [6]:
all_cols = reduce(lambda x, y: x | set(y.columns), df[1:], set(df[0].columns))
common_cols = reduce(lambda x, y: x & set(y.columns), df[1:], set(df[0].columns))
common_cols
not_in_all = all_cols - common_cols
print("Columns missing from at least one dataframe:", not_in_all)

Columns missing from at least one dataframe: {'Public Called IP Address', 'External caller ID number', 'User', 'Call Recording Platform Name', 'Public Calling IP Address', 'Original reason2', 'Device owner UUID', 'Call Recording Trigger', 'Call Recording Result', 'PSTN vendor name2', 'Redirecting party UUID', 'Column1'}

The code chunk below prints the columns present in all the data files.

In [7]:
print(common_cols)

{'Device Mac', 'Route group', 'PSTN legal entity', 'Call outcome', 'OS type', 'Correlation ID', 'Call type', 'Call outcome reason', 'Network call ID', 'Redirect reason', 'Local SessionID', 'Direction', 'Related call ID', 'Transfer related call ID', 'Report time', 'Site timezone', 'Redirecting number', 'Call ID', 'Duration', 'Called number', 'Original reason', 'Remote SessionID', 'Start time', 'Releasing party', 'Client version', 'PSTN provider ID', 'Authorization code', 'Site UUID', 'Answer Indicator', 'Site main number', 'Call transfer time', 'Sub client type', 'Answer time', 'Department ID', 'Local call ID', 'Remote call ID', 'Location', 'Org UUID', 'Release time', 'Ring duration', 'Related reason', 'User number', 'Final local sessionID', 'User type', 'Outbound trunk', 'Client type', 'International Country', 'PSTN vendor name', 'Answered', 'PSTN vendor Org ID', 'Inbound trunk', 'Final remote sessionID', 'Report ID', 'Model', 'User UUID'}

### Reading all the data files
All the datafiles are read with the common columns read first.

In [8]:
df_main = pd.DataFrame(columns=list(common_cols))

In [9]:
i=0; 
for f in files:
    if f.suffix.lower() == ".csv":
        df = pd.read_csv(f, header=0, dtype=str, engine="python", skip_blank_lines=False)
    else:  # .xlsx
        df = pd.read_excel(f, sheet_name=0, header=0, dtype=str)
    df_main = pd.concat([df_main, df], ignore_index=True)
    print(i, f.stem, df.shape)
    i = i + 1

0 April 2024 (56662, 63)
1 April 2025 (63636, 63)
2 August 2024 (63262, 57)
3 August 2025 (57071, 63)
4 December 2024 (49445, 55)
5 February 2025 (63669, 63)
6 January 2025 (62623, 64)
7 July 2024 (62292, 55)
8 July 2025 (60438, 63)
9 June 2024 (56763, 63)
10 June 2025 (54598, 63)
11 March 2025 (59149, 65)
12 May 2024 (62944, 63)
13 May 2025 (55428, 63)
14 November 2024 (49953, 63)
15 October 2024 (62354, 55)
16 September 2024 (61250, 55)

### Converting date to datetime format

In [10]:
df_main["Start time"] = pd.to_datetime(df_main["Start time"], utc=True)

In [11]:
df_main.shape

(1001537, 67)

In [12]:
pwd

'C:\\Users\\akl0407\\Desktop\\Academia\\GitHub\\STAT390_LegalAid_Fall2025\\Internal work of Teams\\Krish'

In [14]:
df_main.to_csv('C:/Users/akl0407/OneDrive - Northwestern University/Back up/2025-26/Fall 2025/LegalAid/AllCallsData.csv',
              index = False)

In [2]:
df_main = pd.read_csv('C:\\Users\\akl0407\\OneDrive - Northwestern University\\Back up\\2025-26\\Fall 2025\\LegalAid\\Processed_data\\all_calls_appended.csv',
                     index_col = None)

C:\Users\akl0407\AppData\Local\Temp\ipykernel_35132\3962911233.py:1: DtypeWarning: Columns (10,11,36,50,56,60,64,65,66,67,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df_main = pd.read_csv('C:\\Users\\akl0407\\OneDrive - Northwestern University\\Back up\\2025-26\\Fall 2025\\LegalAid\\Processed_data\\all_calls_appended.csv',

In [4]:
df_main["Start time"] = pd.to_datetime(df_main["Start time"], utc=True).dt.tz_convert("America/Chicago").dt.tz_localize(None)

In [5]:
df_main['Correlation ID'].nunique()

516786

In [6]:
df_main['Called number'].value_counts()

Called number
13123478300           235325
13123411070           222390
2302                   56716
13124235938            56152
13122296300            36376
                       ...
13129098378                1
17736580657                1
#032235389800045#0         1
13122008607                1
12196144611                1
Name: count, Length: 48821, dtype: int64

In [9]:
df_main.loc[df_main['Called number'] == '13122296300','Correlation ID'].nunique()

18595

In [12]:
df_main.sort_values(by = ['Correlation ID','Start time'], inplace = True)

In [76]:
df_useful = df_main[['Correlation ID', 'Called number', 'PSTN vendor name', 'Direction', 'Duration', 'Original reason', 'Redirect reason',
        'Redirecting number', 'Start time', 'User type', 'User', 'Answered', 'Related reason', 'Release time', 'Answer time']].reset_index(drop = True)

In [78]:
df_useful.loc[df_useful['Correlation ID'] == '00006ccc-8250-4993-90c0-bbfd41f7dd24',:]

,Correlation ID,Called number,PSTN vendor name,Direction,Duration,Original reason,Redirect reason,Redirecting number,Start time,User type,User,Answered,Related reason,Release time,Answer time
2,00006ccc-8250-4993-90c0-bbfd41f7dd24,13123478311,CallTower,TERMINATING,44,NaN,NaN,NaN,2024-12-11 08:41:47.355,User,NaN,True,NaN,2024-12-11T20:42:49.451Z,2024-12-11T20:42:05.392Z
3,00006ccc-8250-4993-90c0-bbfd41f7dd24,13123478300,NaN,ORIGINATING,44,NoAnswer,NoAnswer,13123478311.0,2024-12-11 08:42:05.358,User,NaN,True,CallForwardNoAnswer,2024-12-11T20:42:49.451Z,2024-12-11T20:42:05.392Z
4,00006ccc-8250-4993-90c0-bbfd41f7dd24,13123478300,NaN,TERMINATING,44,NoAnswer,NoAnswer,13123411070.0,2024-12-11 08:42:05.358,VoiceMailRetrieval,NaN,True,NaN,2024-12-11T20:42:49.451Z,2024-12-11T20:42:05.392Z

In [77]:
df_useful

,Correlation ID,Called number,PSTN vendor name,Direction,Duration,Original reason,Redirect reason,Redirecting number,Start time,User type,User,Answered,Related reason,Release time,Answer time
0,00000fe9-dfa0-41c5-986b-d9ce731f2715,13123411070,CallTower,TERMINATING,4,NaN,NaN,NaN,2025-06-27 06:25:23.791,WCCAdapter,NaN,True,NaN,2025-06-27T16:25:28.825Z,2025-06-27T16:25:23.921Z
1,00001e73-ce33-48f1-b531-bddc7ee3965d,13124312299,CallTower,TERMINATING,1961,NaN,NaN,NaN,2024-10-05 07:30:09.903,WCCAdapter,NaN,True,NaN,2024-10-05T18:02:52.100Z,2024-10-05T17:30:10.320Z
2,00006ccc-8250-4993-90c0-bbfd41f7dd24,13123478311,CallTower,TERMINATING,44,NaN,NaN,NaN,2024-12-11 08:41:47.355,User,NaN,True,NaN,2024-12-11T20:42:49.451Z,2024-12-11T20:42:05.392Z
3,00006ccc-8250-4993-90c0-bbfd41f7dd24,13123478300,NaN,ORIGINATING,44,NoAnswer,NoAnswer,13123478311.0,2024-12-11 08:42:05.358,User,NaN,True,CallForwardNoAnswer,2024-12-11T20:42:49.451Z,2024-12-11T20:42:05.392Z
4,00006ccc-8250-4993-90c0-bbfd41f7dd24,13123478300,NaN,TERMINATING,44,NoAnswer,NoAnswer,13123411070.0,2024-12-11 08:42:05.358,VoiceMailRetrieval,NaN,True,NaN,2024-12-11T20:42:49.451Z,2024-12-11T20:42:05.392Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1058103,ffffea69-f56b-4007-9136-97bcef7bb84e,2302,NaN,TERMINATING,153,FollowMe,FollowMe,13123411070,2025-07-22 07:42:53.228,AutomatedAttendantVideo,NaN,True,Deflection,2025-07-22T17:45:27.058Z,2025-07-22T17:42:53.265Z
1058104,ffffea69-f56b-4007-9136-97bcef7bb84e,13123478354,NaN,ORIGINATING,32,Deflection,Deflection,2302,2025-07-22 07:44:36.326,AutomatedAttendantVideo,NaN,True,Deflection,2025-07-22T17:45:27.058Z,2025-07-22T17:44:54.487Z
1058105,ffffea69-f56b-4007-9136-97bcef7bb84e,13123478354,NaN,TERMINATING,32,Deflection,Deflection,13125068649,2025-07-22 07:44:36.384,User,NaN,True,NaN,2025-07-22T17:45:27.058Z,2025-07-22T17:44:54.487Z
1058106,ffffea69-f56b-4007-9136-97bcef7bb84e,13123478300,NaN,ORIGINATING,32,Deflection,NoAnswer,13123478354,2025-07-22 07:44:54.386,User,NaN,True,CallForwardNoAnswer,2025-07-22T17:45:27.058Z,2025-07-22T17:44:54.487Z
1058107,ffffea69-f56b-4007-9136-97bcef7bb84e,13123478300,NaN,TERMINATING,32,Deflection,NoAnswer,13123411070,2025-07-22 07:44:54.449,VoiceMailRetrieval,NaN,True,NaN,2025-07-22T17:45:27.058Z,2025-07-22T17:44:54.487Z

In [62]:
df_frontdesk_rows = df_main.loc[df_main['Called number'] == '13122296300',:]

In [75]:
df_frontdesk_rows.loc[df_frontdesk_rows.Direction == 'TERMINATING']['User type'].value_counts()

User type
User    19344
Name: count, dtype: int64

In [63]:
df_frontdesk_rows['Redirect reason'].value_counts()

Redirect reason
FollowMe      33621
Deflection       40
Name: count, dtype: int64

In [64]:
df_frontdesk_rows['Redirecting number'].value_counts()

Redirecting number
13123411070      17145
13123411070.0    15054
13125068647        410
13125068647.0      300
13125068646        208
13125068646.0      138
13123478342.0      106
13123478342        104
13127536357.0       82
13124312299         28
13127536356.0       26
2302.0              12
13125068649.0       12
13124312299.0       12
13125068649          4
13122296080.0        4
13122296080          4
2302                 3
13122296013          2
13123478399          2
13127536356          2
13122296001.0        2
2303                 1
Name: count, dtype: int64

In [65]:
df_frontdesk_calls = df_useful.loc[df_useful['Correlation ID'].isin(df_frontdesk_rows['Correlation ID']),:].reset_index(drop = True)

In [66]:
df_frontdesk_calls.dtypes

Correlation ID                object
Called number                 object
PSTN vendor name              object
Direction                     object
Duration                       int64
Original reason               object
Redirect reason               object
Redirecting number            object
Start time            datetime64[ns]
User type                     object
User                          object
Answered                        bool
Related reason                object
dtype: object

In [67]:
df_frontdesk_calls.iloc[0:10,:]

,Correlation ID,Called number,PSTN vendor name,Direction,Duration,Original reason,Redirect reason,Redirecting number,Start time,User type,User,Answered,Related reason
0,00024966-393c-467b-ac36-77748d6dd2cf,13122296300,CallTower,TERMINATING,168,NaN,NaN,NaN,2025-02-04 08:17:48.124,User,NaN,True,Deflection
1,00024966-393c-467b-ac36-77748d6dd2cf,13123478312,NaN,TERMINATING,34,Deflection,Deflection,13123411070,2025-02-04 08:19:50.405,User,NaN,True,NaN
2,00024966-393c-467b-ac36-77748d6dd2cf,13123478312,NaN,ORIGINATING,34,Deflection,Deflection,13122296300,2025-02-04 08:19:50.405,User,NaN,True,Deflection
3,00024966-393c-467b-ac36-77748d6dd2cf,13123478300,NaN,ORIGINATING,34,Deflection,NoAnswer,13123478312,2025-02-04 08:20:08.583,User,NaN,True,CallForwardNoAnswer
4,00024966-393c-467b-ac36-77748d6dd2cf,13123478300,NaN,TERMINATING,34,Deflection,NoAnswer,13123411070,2025-02-04 08:20:08.583,VoiceMailRetrieval,NaN,True,NaN
5,0004eb97-96eb-4d42-90bc-0abd9101be7e,13122296300,NaN,TERMINATING,147,NaN,NaN,NaN,2024-04-10 06:15:06.352,User,NaN,True,ConsultativeTransfer
6,000da2e5-6855-4dbd-938d-f8764267364f,13123411070,CallTower,TERMINATING,59,NaN,NaN,NaN,2024-04-19 10:39:19.148,Unknown,NaN,True,NaN
7,000da2e5-6855-4dbd-938d-f8764267364f,13122296300,NaN,ORIGINATING,13,FollowMe,FollowMe,13123411070.0,2024-04-19 10:39:55.960,Unknown,NaN,True,NaN
8,000da2e5-6855-4dbd-938d-f8764267364f,13122296300,NaN,TERMINATING,13,FollowMe,FollowMe,13123411070.0,2024-04-19 10:39:55.960,User,NaN,True,NaN
9,0012b095-3d63-4ef4-a5c6-53482bc4f038,13123411070,CallTower,TERMINATING,5579,NaN,NaN,NaN,2025-08-05 08:10:21.934,WCCAdapter,NaN,True,NaN

In [68]:
adhoc_data_path = 'C:\\Users\\akl0407\\OneDrive - Northwestern University\\Back up\\2025-26\\Fall 2025\\LegalAid\\Adhoc\\Adhoc datasets\\'

In [69]:
df_frontdesk_calls.to_csv(adhoc_data_path + 'frontdesk.csv')

In [70]:
df_frontdesk_calls.groupby('Correlation ID').first()['Called number'].value_counts()

Called number
13123411070    15918
13122296300     2489
13123478342      105
1182              31
13124312299       19
1180              13
13125068646        4
13122296080        4
13125068647        3
13122296346        2
13122296013        1
17732099681        1
13122296342        1
13129561703        1
17734066091        1
13122296321        1
13122296001        1
Name: count, dtype: int64

In [11]:
15.6+2.3

17.9

In [10]:
17134+452

17586

In [79]:
df_main.head()

,Start time,Remote SessionID,Original reason,Route group,User type,Call outcome,Report ID,Outbound trunk,Related reason,Direction,...,Column1,PSTN vendor name2,User,Original reason2,Original called party UUID,Recall Type,Hold Duration,Auto Attendant Key Pressed,Queue Type,Answered Elsewhere
600224,2025-06-27 06:25:23.791,NaN,NaN,NaN,WCCAdapter,Success,b6dc159f-c2b6-3e07-a611-ded33f673ef2,wcc_Pc_tp-ipRwm_ku064NHZiw,NaN,TERMINATING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
929258,2024-10-05 07:30:09.903,NaN,NaN,NaN,WCCAdapter,Success,ec674d05-e84d-3bcc-bf05-3a148df3e1ef,wcc_Iyq3fhu9TjS8hbku8c4Zcg,NaN,TERMINATING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267542,2024-12-11 08:41:47.355,NaN,NaN,NaN,User,Success,aacea7b9-5190-3aab-b568-a5295a04eb5e,NaN,NaN,TERMINATING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267540,2024-12-11 08:42:05.358,41424040edde48e4838bffebf8492c67,NoAnswer,NaN,User,Success,0a882181-8a09-320c-8336-39dfc0bffed4,NaN,CallForwardNoAnswer,ORIGINATING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
267541,2024-12-11 08:42:05.358,NaN,NoAnswer,NaN,VoiceMailRetrieval,Success,5aa6b6a0-dd21-3be4-8edb-77e65f36d3d1,NaN,NaN,TERMINATING,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN