Author: Sabrina Derwent

In [1]:
# Importing relevant libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path
from datetime import datetime

import warnings
warnings.filterwarnings("ignore")

### User input required
Put the data path on your system in the cell below

In [ ]:
#data_path = "C:\\Users\\akl0407\\OneDrive - Northwestern University\\Back up\\2025-26\\Spring 2025\\STAT390\\LegalAid\\Data\\CAR_-_EP_Flow_Activity_Queue__Agent_Names\\"

In [2]:
data_path = "/Users/sabrinaderwent/Desktop/fall25/stat390/CAR_datasets/"

### User input ends

### Reading all filenames in the data folder

In [3]:
folder = Path(data_path)
files = sorted(list(folder.glob("*.csv")) + list(folder.glob("*.xlsx")))
df_main = pd.DataFrame(columns=['Contact Session ID', 'EP Name', 'Flow Name', 'Activity Name', 'Activity Start Timestamp', 
                                'Queue Name', 'Agent Name', 'Termination Reason'])
df_main

Empty DataFrame
Columns: [Contact Session ID, EP Name, Flow Name, Activity Name, Activity Start Timestamp, Queue Name, Agent Name, Termination Reason]
Index: []

### Reading all data files
The code chunk below reads and appends all the CAR data files. The first two rows of each file are blank and thus ignored.

In [4]:
i=0
for f in files:
    i = i + 1
    if f.suffix.lower() == ".csv":
        df = pd.read_csv(f, header=2, dtype=str, engine="python", skip_blank_lines=False)
    else:  # .xlsx
        df = pd.read_excel(f, sheet_name=0, header=2, dtype=str)
    df_main = pd.concat([df_main, df], ignore_index=True)
    print(i, f.stem, df.shape)

1 CAR - EP, Flow, Activity, Queue, & Agent Names (01-12-25 - 01-18-25) (52010, 7)
2 CAR - EP, Flow, Activity, Queue, & Agent Names (01-19-25 - 02-01-25) (95495, 7)
3 CAR - EP, Flow, Activity, Queue, & Agent Names (02-02-25 - 02-15-25) (90056, 7)
4 CAR - EP, Flow, Activity, Queue, & Agent Names (02-16-25 - 03-01-25) (88186, 7)
5 CAR - EP, Flow, Activity, Queue, & Agent Names (03-02-25 - 03-15-25) (86377, 7)
6 CAR - EP, Flow, Activity, Queue, & Agent Names (04-07-24 - 04-20-24) (88766, 7)
7 CAR - EP, Flow, Activity, Queue, & Agent Names (04-21-24 - 05-04-24) (89643, 7)
8 CAR - EP, Flow, Activity, Queue, & Agent Names (05-05-24 - 05-18-24) (82575, 7)
9 CAR - EP, Flow, Activity, Queue, & Agent Names (05-19-24 - 06-01-24) (71103, 7)
10 CAR - EP, Flow, Activity, Queue, & Agent Names (06-02-24 - 06-15-24) (84354, 7)
11 CAR - EP, Flow, Activity, Queue, & Agent Names (06-16-24 - 06-29-24) (82124, 7)
12 CAR - EP, Flow, Activity, Queue, & Agent Names (06-30-24 - 07-13-24) (79752, 7)
13 CAR - EP, Flow, Activity, Queue, & Agent Names (07-14-24 - 07-27-24) (85110, 7)
14 CAR - EP, Flow, Activity, Queue, & Agent Names (07-28-24 - 08-10-24) (84627, 7)
15 CAR - EP, Flow, Activity, Queue, & Agent Names (08-11-24 - 08-24-24) (91622, 7)
16 CAR - EP, Flow, Activity, Queue, & Agent Names (08-24-24 - 09-07-24) (90040, 7)
17 CAR - EP, Flow, Activity, Queue, & Agent Names (09-08-24 - 09-21-24) (96581, 7)
18 CAR - EP, Flow, Activity, Queue, & Agent Names (09-22-24 - 10-05-24) (89446, 7)
19 CAR - EP, Flow, Activity, Queue, & Agent Names (10-06-24 - 10-19-24) (81700, 7)
20 CAR - EP, Flow, Activity, Queue, & Agent Names (10-20-24 - 11-02-24) (88430, 7)
21 CAR - EP, Flow, Activity, Queue, & Agent Names (11-03-24 - 11-16-24) (81614, 7)
22 CAR - EP, Flow, Activity, Queue, & Agent Names (11-17-24 - 11-30-24) (66216, 7)
23 CAR - EP, Flow, Activity, Queue, & Agent Names (12-01-24 - 12-14-24) (92220, 7)
24 CAR - EP, Flow, Activity, Queue, & Agent Names (12-15-24 - 12-28-24) (62143, 7)
25 CAR - EP, Flow, Activity, Queue, & Agent Names (12-29-24 - 01-11-25) (75356, 7)
26 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 3-16 to 3-22-25 (45326, 8)
27 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 3-30 to 4-5-25 (45072, 8)
28 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-13 to 4-19-25 (41088, 8)
29 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-20 to 4-26-25 (46686, 8)
30 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-27 to 5-3-25 (44169, 8)
31 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 4-6 to 4-12-25 (46630, 8)
32 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-11 to 5-17-25 (43268, 8)
33 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-18 to 5-24-25 (45104, 8)
34 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-25 to 5-31-25 (36851, 8)
35 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 5-4 to 5-10-25 (43955, 8)
36 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-1 to 6-7-25 (44523, 8)
37 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-15 to 6-21-25 (37234, 8)
38 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-22 to 6-28-25 (45394, 8)
39 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-29 to 7-5-25 (38300, 8)
40 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 6-8 to 6-14-25 (46728, 8)
41 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-13 to 7-19-25 (45706, 8)
42 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-20 to 7-26-25 (45328, 8)
43 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-28 ro 8-2-25 (46237, 8)
44 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 7-6 to 7-12-25 (48707, 8)
45 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-10 to 8-16-25 (44095, 8)
46 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-17 to 8-23-25 (47062, 8)
47 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-24 to 8-30-25 (45113, 8)
48 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-3 to 8-9-25 (44706, 8)
49 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 8-31 to 9-6-25 (36177, 8)
50 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 9-14 to 9-20-25 (45958, 8)
51 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 9-21 to 9-30-25 (60381, 8)
52 CAR - EP, Flow, Activity, Queue, &amp; Agent Names 9-7 to 9-13-25 (45304, 8)
53 CAR - EP, Flow, Activity, Queue, &amp; Agent Names3-23 to 3-29-25 (47978, 8)

In [ ]:
df_main.head()

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason
0,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,NaN,2025/01/14 12:39:32 PM,NaN,NaN,NaN
1,001a3748-8d50-4550-8461-33547983deb0,NaN,LACMain,NaN,2025/01/14 12:39:32 PM,NaN,NaN,NaN
2,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/01/14 12:39:32 PM,NaN,NaN,NaN
3,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,LACMain,NaN,2025/01/14 12:39:32 PM,NaN,NaN,NaN
4,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,MainMenu,2025/01/14 12:39:45 PM,NaN,NaN,NaN

### Time datatype conversion
The code chunk below converts time from string to datetime datatype.

In [ ]:
df_main["Activity Start Timestamp"] = df_main["Activity Start Timestamp"].apply(
    lambda x: datetime.strptime(x, "%Y/%m/%d %I:%M:%S %p"))

In [ ]:
# Checking the datatype of all columns
df_main.dtypes

Contact Session ID                  object
EP Name                             object
Flow Name                           object
Activity Name                       object
Activity Start Timestamp    datetime64[ns]
Queue Name                          object
Agent Name                          object
Termination Reason                  object
dtype: object

In [ ]:
# Creating a new column 'hour' as it will be useful to visualize peak calling hours
df_main["hour"] = df_main["Activity Start Timestamp"].dt.hour

In [ ]:
# create date category in datetie
df_main["date"] = df_main["Activity Start Timestamp"].dt.date
df_main["date"] = pd.to_datetime(df_main["date"])

## Consistency Check for Call Outcomes

In [5]:
df_main.head()

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason
0,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,NaN,2025/01/14 12:39:32 PM,NaN,NaN,NaN
1,001a3748-8d50-4550-8461-33547983deb0,NaN,LACMain,NaN,2025/01/14 12:39:32 PM,NaN,NaN,NaN
2,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/01/14 12:39:32 PM,NaN,NaN,NaN
3,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,LACMain,NaN,2025/01/14 12:39:32 PM,NaN,NaN,NaN
4,001a3748-8d50-4550-8461-33547983deb0,Main Number Telephony EP,NaN,MainMenu,2025/01/14 12:39:45 PM,NaN,NaN,NaN

In [13]:
# getting the last activity for each contact session id
last = df_main.groupby("Contact Session ID")['Activity Name'].last().reset_index().rename(columns = {"Activity Name": "Last Activity"})
last

                          Contact Session ID                  Last Activity
0       00002422-f51f-458b-82d6-cfa5a3f36fd9  StaffDirectoryEnglishTransfer
1       0000a8d5-cecb-46b1-82cf-b7ce07d85b24                     ClosedMenu
2       00011655-35de-476f-9a8c-dd48ed4d914a             FrontDeskTransfer2
3       00014a58-a6ce-4cb2-a529-d55e2c9c304d                ClosedQueueMenu
4       00015327-f646-462f-a585-0552331eed4e             DisconnectContact1
...                                      ...                            ...
248437  fffe199f-3382-43e1-b8a5-efb9d55bdb23             FarmworkerMainMenu
248438  fffe91b1-c54d-4b1e-b19d-1ef78e4a8871             FrontDeskTransfer1
248439  fffed0e4-d57d-42dc-8d9e-725ce451fa9e                ClosedQueueMenu
248440  fffeef9f-11f2-42c8-80e3-511a9a01d66f          LanguageSelectionMenu
248441  ffffa50d-6d02-4281-9141-087a806a8343          LanguageSelectionMenu

[248442 rows x 2 columns]

### LanguageSelectionMenu

In [ ]:
# verifying that there are the same number of rows as in Krish's analysis
last[last['Last Activity'] == "LanguageSelectionMenu"].shape

(27545, 2)

In [52]:
# finding contact sessions that have the last activity as "LanguageSelectionMenu"
lang_journey = df_main[df_main['Contact Session ID'].isin(last[last['Last Activity'] == "LanguageSelectionMenu"]['Contact Session ID'])]
lang_journey

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason
94,00551319-112a-4367-8a20-7558c5f3d631,Main Number Telephony EP,NaN,NaN,2025/01/17 10:06:01 AM,NaN,NaN,NaN
95,00551319-112a-4367-8a20-7558c5f3d631,NaN,LACMain,NaN,2025/01/17 10:06:01 AM,NaN,NaN,NaN
96,00551319-112a-4367-8a20-7558c5f3d631,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/01/17 10:06:01 AM,NaN,NaN,NaN
97,00551319-112a-4367-8a20-7558c5f3d631,Main Number Telephony EP,LACMain,NaN,2025/01/17 10:06:01 AM,NaN,NaN,NaN
98,00551319-112a-4367-8a20-7558c5f3d631,Main Number Telephony EP,NaN,NaN,2025/01/17 10:06:06 AM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
3328609,5f00bbb2-c1d0-4271-b902-acd85bfbf615,Main Number Telephony EP,NaN,NaN,2025/03/29 07:40:08 PM,NaN,NaN,Customer Left
3328622,c30580e4-54b3-4122-937c-9672bf1adf24,Main Number Telephony EP,NaN,NaN,2025/03/29 10:36:18 PM,NaN,NaN,NaN
3328623,c30580e4-54b3-4122-937c-9672bf1adf24,NaN,LACMain,NaN,2025/03/29 10:36:18 PM,NaN,NaN,NaN
3328624,c30580e4-54b3-4122-937c-9672bf1adf24,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/03/29 10:36:18 PM,NaN,NaN,NaN
3328625,c30580e4-54b3-4122-937c-9672bf1adf24,Main Number Telephony EP,NaN,NaN,2025/03/29 10:36:18 PM,NaN,NaN,Customer Left

In [ ]:
# seeing if there are other possible termination reasons that would not be considered abandonment
filtered = lang_journey[
    (lang_journey['Termination Reason'].notna()) &
    (lang_journey['Termination Reason'] != "Customer Left")
]

print(filtered['Termination Reason'].unique())

['NO_ANSWER_FROM_CUSTOMER' 'System Error']

In [69]:
no_answer = df_main[df_main['Contact Session ID'].isin(lang_journey[lang_journey['Termination Reason'] == "NO_ANSWER_FROM_CUSTOMER"]['Contact Session ID'])]
no_answer.groupby("Contact Session ID").tail(3)

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason
2084904,5f60379e-5c51-4111-b433-ce8d821f74e1,NaN,LACMain,NaN,2025/03/17 06:38:06 PM,NaN,NaN,NaN
2084905,5f60379e-5c51-4111-b433-ce8d821f74e1,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/03/17 06:38:06 PM,NaN,NaN,NaN
2084906,5f60379e-5c51-4111-b433-ce8d821f74e1,Main Number Telephony EP,NaN,NaN,2025/03/17 06:38:06 PM,NaN,NaN,NO_ANSWER_FROM_CUSTOMER
2096099,7f40990c-7703-41ee-966a-c0ec2831823a,NaN,LACMain,NaN,2025/03/19 08:50:01 AM,NaN,NaN,NaN
2096100,7f40990c-7703-41ee-966a-c0ec2831823a,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/03/19 08:50:01 AM,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
3312410,f0d376c8-b3b0-4a97-80f9-96727bd1e06a,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/03/26 04:59:47 PM,NaN,NaN,NaN
3312411,f0d376c8-b3b0-4a97-80f9-96727bd1e06a,Main Number Telephony EP,NaN,NaN,2025/03/26 04:59:47 PM,NaN,NaN,NO_ANSWER_FROM_CUSTOMER
3328284,a564c058-acc4-4462-9771-5604f72de3f4,NaN,LACMain,NaN,2025/03/28 10:44:49 PM,NaN,NaN,NaN
3328285,a564c058-acc4-4462-9771-5604f72de3f4,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/03/28 10:44:49 PM,NaN,NaN,NaN
3328286,a564c058-acc4-4462-9771-5604f72de3f4,Main Number Telephony EP,NaN,NaN,2025/03/28 10:44:49 PM,NaN,NaN,NO_ANSWER_FROM_CUSTOMER

In [76]:
no_answer = df_main[df_main['Contact Session ID'].isin(lang_journey[lang_journey['Termination Reason'] == "System Error"]['Contact Session ID'])]
no_answer.groupby("Contact Session ID").tail(1)

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason
2094727,be2d7953-d02c-441c-bb81-8c6b466c7f01,Main Number Telephony EP,NaN,NaN,2025/03/18 08:14:46 PM,NaN,NaN,System Error
2113657,c7c6efd0-125e-4302-9208-4229cd4b36c9,Main Number Telephony EP,NaN,NaN,2025/03/21 08:42:18 AM,NaN,NaN,System Error
2120742,ffc6a5a3-a749-4877-b9e0-873dac625704,Main Number Telephony EP,NaN,NaN,2025/03/22 02:29:41 PM,NaN,NaN,System Error
2124998,6765f0cb-24ce-43d6-aecd-590d370ac769,Main Number Telephony EP,NaN,NaN,2025/03/31 10:36:31 AM,NaN,NaN,System Error
2125233,8c2add00-3f83-4ef9-a47f-15a0c9f33ed2,Main Number Telephony EP,NaN,NaN,2025/03/31 10:44:53 AM,NaN,NaN,System Error
...,...,...,...,...,...,...,...,...
3275265,50c9a2c3-6da9-407f-a135-681b47bb3c7f,Main Number Telephony EP,NaN,NaN,2025/09/12 10:14:47 AM,NaN,NaN,System Error
3275287,2c532fe4-5a07-416e-97f9-3b34c62c2809,Main Number Telephony EP,NaN,NaN,2025/09/12 10:15:34 AM,NaN,NaN,System Error
3275992,575baf0f-28e2-403b-88f5-658a73f78ba5,Main Number Telephony EP,NaN,NaN,2025/09/12 10:54:30 AM,NaN,NaN,System Error
3280531,07087cfa-6c90-4f4f-9f0f-30a2a4afa69b,Main Number Telephony EP,NaN,NaN,2025/09/13 02:51:35 PM,NaN,NaN,System Error
3320541,74d8b871-d9fd-4bf1-8a9a-a96998225624,Main Number Telephony EP,NaN,NaN,2025/03/27 04:22:06 PM,NaN,NaN,System Error

There are 154 calls that ended in the language selection menu due to a system error. For this analysis, we are only focusing on the last activity to classify outcomes as termination reasons are only present for a 1/3 of the data. However, within that 1/3 of that data we can classify further and gain a more precise outcome. For example, 154/27545 (0.5%) of calls could be classified as neutral based on their termination reason. This is something that could be expanded upon for presentation 5.  

Overall, if a call ends in LanguageSelectionMenu it is a negative outcome because the caller should be going somewhere else to receive help.

### Repeating this process with every last activity

In [92]:
# List of all last activities
last_act = [
    "LanguageSelectionMenu","ClinicVoicemailTransfer","MainMenu", "DisconnectContact1", "LegalMenu2", "FarmworkerMainMenu",
    "SetCallerID", "LegalServerScreenPop", "FrontDeskTransfer1", "ClosedMenu",
    "FrontDeskTransfer2", "OtherLegalMenu", "StaffDirectorySpanishTransfer",
    "FrontDeskTransfer", "TenantMenu", "CriminalRecordsVoicemailTransfer",
    "OtherLegalOtherMenu", "DivorceOrParentingMenu", "QueueMenu1", "LegalMenu1",
    "SeniorsMenu", "TenantDeterrenceMenu", "HousingMenu", "HIVVoicemailTransfer",
    "PlayMOH300s", "HIVMenu", "ScreenPopProcessComplete", "AddressFaxHoursMenu",
    "PreTenantMenu", "FamilyMenu", "FrontDeskTransfer3", "ChildSupportMenu",
    "ImmigrationMenu", "SeniorsADAPTMenu", "OtherLegalPersonalInjuryMenu",
    "OtherLegalCriminalCaseMenu", "SuburbsOrCityMenu", "SuburbanSeniorsMenu",
    "TransferToSafeHaven", "SimpleDivorceMenu", "BenefitsMenu",
    "SubSeniorPreQueueMessage1_1", "ThankYouGoodbye", "IntakePreQueueMessage1",
    "SeniorsConfirmationMenu", "VeteransBenefitsVoicemailTransfer",
    "EmploymentMenu", "No activity", "DisconnectContact2",
    "TraffickingVoicemailTransfer", "AppointmentMenu", "SeniorNotCookCoMenu",
    "ImmigrationOtherMenu", "HolidayPrompt", "DisconnectCallbackContact",
    "MigrantVoicemailTransfer", "ComplimentOrComplaintMenu", "PreQueueMessage2",
    "HelpWithLegalorOtherReasonMenu", "DisconnectContact", "WorkersCompMenu",
    "GetLoggedInSubSeniorTenantAgents", "ReadANI", "PlayErrorMessage",
    "CallbackRetry", "GetLoggedInSubSeniorOtherAgents", "CollectCallbackNumber",
    "ConfirmCallbackNumber", "SubSeniorPreQueueMessage1_2",
    "GetLoggedInSubSeniorOtherSPAgents", "SubSeniorOtherQueue",
    "GetLoggedInConsumerAgents", "ImmigrationSPQueue",
    "GetLoggedInOtherSubSeniorsAgents", "SubSeniorTenantQueue", "EducationSPQueue",
    "PlayCCBConfirmation", "SubSeniorHomeownerQueue", "SubSeniorConsumerQueue",
    "GetLoggedInSubSeniorTenantSPAgents"
]

# Store results for each activity
results = {}

for cat in last_act:
    # Find sessions whose LAST activity = this category
    ids = last[last["Last Activity"] == cat]["Contact Session ID"]

    # Extract full journeys for those sessions
    journeys = df_main[df_main["Contact Session ID"].isin(ids)]
    journeys = journeys.groupby('Contact Session ID').tail()

    # Save into dictionary
    results[cat] = {
        "ids": ids,
        "journeys": journeys
    }

results

{'LanguageSelectionMenu': {'ids': 5         000183bb-0f39-4d50-87b9-747243d939bc
  9         00031192-99dd-4eec-815e-1d54abedc153
  13        0003dd1d-d68d-4d9f-9a0e-d9f908c7b38e
  14        0003e265-6287-4644-9032-8843c8fbfff7
  30        00087454-70f3-4d9a-9830-c92164b3ea18
                            ...
  248422    fff917e8-0ddc-43eb-a390-8947a1f0ea1a
  248432    fffc3bdf-8989-46ba-ad14-a5b3755017b0
  248436    fffd0f07-35ae-4029-8d41-b355479242a2
  248440    fffeef9f-11f2-42c8-80e3-511a9a01d66f
  248441    ffffa50d-6d02-4281-9141-087a806a8343
  Name: Contact Session ID, Length: 27545, dtype: object,
  'journeys':                            Contact Session ID                   EP Name  \
  94       00551319-112a-4367-8a20-7558c5f3d631  Main Number Telephony EP
  95       00551319-112a-4367-8a20-7558c5f3d631                       NaN
  96       00551319-112a-4367-8a20-7558c5f3d631  Main Number Telephony EP
  97       00551319-112a-4367-8a20-7558c5f3d631  Main Number Telephony EP
  98       00551319-112a-4367-8a20-7558c5f3d631  Main Number Telephony EP
  ...                                       ...                       ...
  3328609  5f00bbb2-c1d0-4271-b902-acd85bfbf615  Main Number Telephony EP
  3328622  c30580e4-54b3-4122-937c-9672bf1adf24  Main Number Telephony EP
  3328623  c30580e4-54b3-4122-937c-9672bf1adf24                       NaN
  3328624  c30580e4-54b3-4122-937c-9672bf1adf24  Main Number Telephony EP
  3328625  c30580e4-54b3-4122-937c-9672bf1adf24  Main Number Telephony EP

          Flow Name          Activity Name Activity Start Timestamp Queue Name  \
  94            NaN                    NaN   2025/01/17 10:06:01 AM        NaN
  95        LACMain                    NaN   2025/01/17 10:06:01 AM        NaN
  96            NaN  LanguageSelectionMenu   2025/01/17 10:06:01 AM        NaN
  97        LACMain                    NaN   2025/01/17 10:06:01 AM        NaN
  98            NaN                    NaN   2025/01/17 10:06:06 AM        NaN
  ...           ...                    ...                      ...        ...
  3328609       NaN                    NaN   2025/03/29 07:40:08 PM        NaN
  3328622       NaN                    NaN   2025/03/29 10:36:18 PM        NaN
  3328623   LACMain                    NaN   2025/03/29 10:36:18 PM        NaN
  3328624       NaN  LanguageSelectionMenu   2025/03/29 10:36:18 PM        NaN
  3328625       NaN                    NaN   2025/03/29 10:36:18 PM        NaN

          Agent Name Termination Reason
  94             NaN                NaN
  95             NaN                NaN
  96             NaN                NaN
  97             NaN                NaN
  98             NaN                NaN
  ...            ...                ...
  3328609        NaN      Customer Left
  3328622        NaN                NaN
  3328623        NaN                NaN
  3328624        NaN                NaN
  3328625        NaN      Customer Left

  [136549 rows x 8 columns]},
 'ClinicVoicemailTransfer': {'ids': 10        0003369c-5377-4d88-9c5d-779a75d2de22
  24        000619cd-0946-4ba8-97fa-94cfd34c7768
  26        0007108a-5d96-44c6-b0b0-70b248af81b5
  37        000a9e4a-e954-444e-b716-883ff71601f5
  43        000caba5-fffb-4785-8a7d-9e1021caa8d5
                            ...
  248381    ffefe646-0e5f-4ad0-9b0e-d6d656767e22
  248398    fff3f0cb-5907-4e8c-bf9c-e76cf0928215
  248407    fff5ca16-2e1f-4c70-9361-a4ab4bcab275
  248410    fff6528c-3f65-4526-8bdb-5e8c88fd5c9c
  248416    fff72f66-a1e3-4dd7-bede-03e4b77a1a89
  Name: Contact Session ID, Length: 25721, dtype: object,
  'journeys':                            Contact Session ID  \
  89       0053f689-47d7-43fc-abe9-0ffe71bbdb10
  90       0053f689-47d7-43fc-abe9-0ffe71bbdb10
  91       0053f689-47d7-43fc-abe9-0ffe71bbdb10
  92       0053f689-47d7-43fc-abe9-0ffe71bbdb10
  93       0053f689-47d7-43fc-abe9-0ffe71bbdb10
  ...                                       ...
  3328581  558f243a-6e4f-4d8a-8484-2494c49a0e70
  3328582  558f243a-6e4f-4d8a-8484-2494c49a0e70
  3328583  558f243a-6e4f-4d8a-8484-2494c49a0e70
  3328584  558f243a-6e4f-4d8a-8484-2494c49a0e70
  3328585  558f243a-6e4f-4d8a-8484-2494c49a0e70

                                           EP Name Flow Name Activity Name  \
  89                                           NaN       NaN           NaN
  90                Closed Queue Menu Telephony EP       NaN           NaN
  91                Closed Queue Menu Telephony EP       NaN           NaN
  92                Closed Queue Menu Telephony EP       NaN           NaN
  93                Closed Queue Menu Telephony EP       NaN           NaN
  ...                                          ...       ...           ...
  3328581                                      NaN       NaN           NaN
  3328582  Closed Hours-Holidays Menu Telephony EP       NaN           NaN
  3328583  Closed Hours-Holidays Menu Telephony EP       NaN           NaN
  3328584  Closed Hours-Holidays Menu Telephony EP       NaN           NaN
  3328585  Closed Hours-Holidays Menu Telephony EP       NaN           NaN

          Activity Start Timestamp                 Queue Name Agent Name  \
  89        2025/01/15 08:49:05 AM  Clinic Voicemail Transfer        NaN
  90        2025/01/15 08:49:05 AM                        NaN        NaN
  91        2025/01/15 08:49:05 AM  Clinic Voicemail Transfer  CBT Agent
  92        2025/01/15 08:49:23 AM  Clinic Voicemail Transfer  CBT Agent
  93        2025/01/15 08:49:58 AM  Clinic Voicemail Transfer  CBT Agent
  ...                          ...                        ...        ...
  3328581   2025/03/29 03:13:00 PM  Clinic Voicemail Transfer        NaN
  3328582   2025/03/29 03:13:00 PM                        NaN        NaN
  3328583   2025/03/29 03:13:01 PM  Clinic Voicemail Transfer  CBT Agent
  3328584   2025/03/29 03:13:19 PM  Clinic Voicemail Transfer  CBT Agent
  3328585   2025/03/29 03:15:39 PM  Clinic Voicemail Transfer  CBT Agent

          Termination Reason
  89                     NaN
  90                     NaN
  91                     NaN
  92                     NaN
  93                     NaN
  ...                    ...
  3328581                NaN
  3328582                NaN
  3328583                NaN
  3328584                NaN
  3328585      Customer Left

  [128605 rows x 8 columns]},
 'MainMenu': {'ids': 6         00023e47-b722-4e2f-b2e2-855911d085fd
  38        000aceb4-5490-44e3-b941-413fee12cd68
  45        000d076f-3aec-4274-b576-f78a48701710
  54        00107bcd-4ea0-4eab-a53d-b76db238fc86
  117       0020ac59-1bf1-47a9-b7cc-2ffd52316102
                            ...
  248351    ffe897b8-4ea2-4340-b99a-a0f651ef3505
  248355    ffe9e86e-6cbc-4192-a56f-071623d0481e
  248363    ffeb71be-37f6-4307-828b-ceb73541a484
  248392    fff30d2d-1493-4809-9c97-ee66da7649d5
  248402    fff489a1-5e43-4595-af03-8e4f2cff518a
  Name: Contact Session ID, Length: 13075, dtype: object,
  'journeys':                            Contact Session ID                   EP Name  \
  399      01936273-982f-4586-8e52-bc72636a719d                       NaN
  400      01936273-982f-4586-8e52-bc72636a719d  Main Number Telephony EP
  401      01936273-982f-4586-8e52-bc72636a719d  Main Number Telephony EP
  402      01936273-982f-4586-8e52-bc72636a719d  Main Number Telephony EP
  403      01936273-982f-4586-8e52-bc72636a719d  Main Number Telephony EP
  ...                                       ...                       ...
  3327866  95b86a6e-c608-49ef-b272-e023344c38a7  Main Number Telephony EP
  3327867  95b86a6e-c608-49ef-b272-e023344c38a7  Main Number Telephony EP
  3327868  95b86a6e-c608-49ef-b272-e023344c38a7  Main Number Telephony EP
  3327891  95b86a6e-c608-49ef-b272-e023344c38a7  Main Number Telephony EP
  3327892  95b86a6e-c608-49ef-b272-e023344c38a7  Main Number Telephony EP

          Flow Name          Activity Name Activity Start Timestamp Queue Name  \
  399       LACMain                    NaN   2025/01/15 03:13:15 PM        NaN
  400           NaN  LanguageSelectionMenu   2025/01/15 03:13:15 PM        NaN
  401       LACMain                    NaN   2025/01/15 03:13:15 PM        NaN
  402           NaN               MainMenu   2025/01/15 03:13:26 PM        NaN
  403           NaN                    NaN   2025/01/15 03:14:03 PM        NaN
  ...           ...                    ...                      ...        ...
  3327866       NaN  LanguageSelectionMenu   2025/03/28 04:01:36 PM        NaN
  3327867   LACMain                    NaN   2025/03/28 04:01:36 PM        NaN
  3327868       NaN               MainMenu   2025/03/28 04:01:44 PM        NaN
  3327891       NaN               MainMenu   2025/03/28 04:03:05 PM        NaN
  3327892       NaN                    NaN   2025/03/28 04:03:05 PM        NaN

          Agent Name Termination Reason
  399            NaN                NaN
  400            NaN                NaN
  401            NaN                NaN
  402            NaN                NaN
  403            NaN                NaN
  ...            ...                ...
  3327866        NaN                NaN
  3327867        NaN                NaN
  3327868        NaN                NaN
  3327891        NaN                NaN
  3327892        NaN      Customer Left

  [65375 rows x 8 columns]},
 'DisconnectContact1': {'ids': 4         00015327-f646-462f-a585-0552331eed4e
  17        0004f7a4-ea7f-4d4e-9b63-33839fe9653d
  63        0011f4fb-1555-4932-a934-24ce1530dd11
  101       001d4ba0-a384-4c4b-ae8a-bdda3e1119dc
  120       00211bb8-42c3-4c33-88af-1f6ae6fb4c7d
                            ...
  248266    ffd3a766-00ba-4f92-9645-f19a7d0ffe8e
  248290    ffd9a39e-d6f9-487f-b309-d5b2392b0186
  248308    ffdd1b59-9c77-496c-8321-dec23cc06bb2
  248349    ffe84b1f-b42e-453c-b85e-7f173d8e33e0
  248386    fff1f3f2-f4b7-4f80-b19d-ab1b6377684d
  Name: Contact Session ID, Length: 12010, dtype: object,
  'journeys':                            Contact Session ID  \
  580      02de749f-a394-47f9-aadb-daa6ed231535
  581      02de749f-a394-47f9-aadb-daa6ed231535
  582      02de749f-a394-47f9-aadb-daa6ed231535
  583      02de749f-a394-47f9-aadb-daa6ed231535
  584      02de749f-a394-47f9-aadb-daa6ed231535
  ...                                       ...
  3328569  370220fd-8846-4112-9cf8-2725732a53b1
  3328570  370220fd-8846-4112-9cf8-2725732a53b1
  3328571  370220fd-8846-4112-9cf8-2725732a53b1
  3328572  370220fd-8846-4112-9cf8-2725732a53b1
  3328573  370220fd-8846-4112-9cf8-2725732a53b1

                                           EP Name                Flow Name  \
  580                     Main Number Telephony EP                      NaN
  581                                          NaN  ClosedHoursHolidaysMenu
  582      Closed Hours-Holidays Menu Telephony EP                      NaN
  583      Closed Hours-Holidays Menu Telephony EP                      NaN
  584      Closed Hours-Holidays Menu Telephony EP                      NaN
  ...                                          ...                      ...
  3328569                 Main Number Telephony EP                  LACMain
  3328570                                      NaN  ClosedHoursHolidaysMenu
  3328571  Closed Hours-Holidays Menu Telephony EP                      NaN
  3328572  Closed Hours-Holidays Menu Telephony EP                      NaN
  3328573  Closed Hours-Holidays Menu Telephony EP                      NaN

                Activity Name Activity Start Timestamp Queue Name Agent Name  \
  580                MainMenu   2025/01/13 04:35:09 PM        NaN        NaN
  581                     NaN   2025/01/13 04:35:31 PM        NaN        NaN
  582              ClosedMenu   2025/01/13 04:35:31 PM        NaN        NaN
  583      DisconnectContact1   2025/01/13 04:35:44 PM        NaN        NaN
  584                     NaN   2025/01/13 04:35:44 PM        NaN        NaN
  ...                     ...                      ...        ...        ...
  3328569                 NaN   2025/03/29 03:07:34 PM        NaN        NaN
  3328570                 NaN   2025/03/29 03:07:46 PM        NaN        NaN
  3328571          ClosedMenu   2025/03/29 03:07:46 PM        NaN        NaN
  3328572  DisconnectContact1   2025/03/29 03:08:08 PM        NaN        NaN
  3328573                 NaN   2025/03/29 03:08:08 PM        NaN        NaN

          Termination Reason
  580                    NaN
  581                    NaN
  582                    NaN
  583                    NaN
  584                    NaN
  ...                    ...
  3328569                NaN
  3328570                NaN
  3328571                NaN
  3328572                NaN
  3328573      Customer Left

  [60050 rows x 8 columns]},
 'LegalMenu2': {'ids': 8         0002f64b-59d3-4cba-885c-83b997d2fc73
  11        000353fe-3aec-4d65-b818-0d2598beb909
  94        001ac32a-2785-45e6-86c9-5a7d20835d6c
  156       0026dacf-01cc-47d8-9bdd-41216e263752
  185       002da9cd-0209-40e9-9d13-ff3d02c6ca7e
                            ...
  248358    ffeb296c-7944-4ddf-aefa-6432f4d2e182
  248377    ffeee726-b0fa-4096-a4be-7af781fa6717
  248387    fff21aef-d339-4624-a608-75819dbfe1fe
  248395    fff36943-fc2a-4643-b877-01212cb56dad
  248419    fff81782-e4b9-4d33-8b02-fda08204ed29
  Name: Contact Session ID, Length: 11987, dtype: object,
  'journeys':                            Contact Session ID  \
  378      018c4f10-6a2e-4957-871b-e26c6034dc6d
  379      018c4f10-6a2e-4957-871b-e26c6034dc6d
  380      018c4f10-6a2e-4957-871b-e26c6034dc6d
  381      018c4f10-6a2e-4957-871b-e26c6034dc6d
  382      018c4f10-6a2e-4957-871b-e26c6034dc6d
  ...                                       ...
  3327555  1ae6d5f3-a75e-4364-aac6-d83eba15939d
  3327556  1ae6d5f3-a75e-4364-aac6-d83eba15939d
  3327561  1ae6d5f3-a75e-4364-aac6-d83eba15939d
  3327562  1ae6d5f3-a75e-4364-aac6-d83eba15939d
  3327564  1ae6d5f3-a75e-4364-aac6-d83eba15939d

                                            EP Name         Flow Name  \
  378      Pre-Legal Menu Seniors Menu Telephony EP               NaN
  379                                           NaN         LegalMenu
  380                       Legal Menu Telephony EP               NaN
  381                       Legal Menu Telephony EP               NaN
  382                       Legal Menu Telephony EP               NaN
  ...                                           ...               ...
  3327555                                       NaN  LegalHousingMenu
  3327556           Legal Housing Menu Telephony EP               NaN
  3327561                                       NaN         LegalMenu
  3327562                   Legal Menu Telephony EP               NaN
  3327564                   Legal Menu Telephony EP               NaN

          Activity Name Activity Start Timestamp Queue Name Agent Name  \
  378       SeniorsMenu   2025/01/14 01:12:30 PM        NaN        NaN
  379               NaN   2025/01/14 01:12:41 PM        NaN        NaN
  380        LegalMenu1   2025/01/14 01:12:41 PM        NaN        NaN
  381        LegalMenu2   2025/01/14 01:13:14 PM        NaN        NaN
  382               NaN   2025/01/14 01:13:14 PM        NaN        NaN
  ...               ...                      ...        ...        ...
  3327555           NaN   2025/03/28 03:31:17 PM        NaN        NaN
  3327556   HousingMenu   2025/03/28 03:31:17 PM        NaN        NaN
  3327561           NaN   2025/03/28 03:31:45 PM        NaN        NaN
  3327562    LegalMenu2   2025/03/28 03:31:45 PM        NaN        NaN
  3327564           NaN   2025/03/28 03:32:47 PM        NaN        NaN

          Termination Reason
  378                    NaN
  379                    NaN
  380                    NaN
  381                    NaN
  382                    NaN
  ...                    ...
  3327555                NaN
  3327556                NaN
  3327561                NaN
  3327562                NaN
  3327564      Customer Left

  [59935 rows x 8 columns]},
 'FarmworkerMainMenu': {'ids': 12        0003aec2-1d09-47d3-8d08-937b92764eee
  22        0005a285-d65d-4f64-8b6d-a7d2e27dcfdc
  48        000dfe16-65d2-47b7-ac80-e1bc7770ab1f
  67        00129031-2896-433f-a826-fdaed2174611
  97        001b716a-a16c-4e77-b26c-6c96a473b689
                            ...
  248291    ffda1fb7-1cea-4bcb-8b98-59dd2d8d1f5c
  248333    ffe4271a-cbae-4307-901e-10200d237541
  248393    fff32f97-537d-4f5d-8dcb-c7a71cace9c2
  248421    fff8e577-b64b-41ba-83a9-3286c28dab3b
  248437    fffe199f-3382-43e1-b8a5-efb9d55bdb23
  Name: Contact Session ID, Length: 9640, dtype: object,
  'journeys':                            Contact Session ID  \
  207      00eda02a-79b8-49e3-8a7d-a50446920c55
  208      00eda02a-79b8-49e3-8a7d-a50446920c55
  209      00eda02a-79b8-49e3-8a7d-a50446920c55
  210      00eda02a-79b8-49e3-8a7d-a50446920c55
  211      00eda02a-79b8-49e3-8a7d-a50446920c55
  ...                                       ...
  3328617  6a3727d7-65b6-4dc8-9808-6a571aae69a8
  3328618  6a3727d7-65b6-4dc8-9808-6a571aae69a8
  3328619  6a3727d7-65b6-4dc8-9808-6a571aae69a8
  3328620  469070a2-a722-47b7-b511-f65f5be8d21b
  3328621  6a3727d7-65b6-4dc8-9808-6a571aae69a8

                                       EP Name       Flow Name  \
  207                                      NaN  FarmworkerMain
  208      Farmworker Main Number Telephony EP             NaN
  209      Farmworker Main Number Telephony EP  FarmworkerMain
  210      Farmworker Main Number Telephony EP             NaN
  211      Farmworker Main Number Telephony EP             NaN
  ...                                      ...             ...
  3328617  Farmworker Main Number Telephony EP             NaN
  3328618  Farmworker Main Number Telephony EP  FarmworkerMain
  3328619  Farmworker Main Number Telephony EP             NaN
  3328620  Farmworker Main Number Telephony EP             NaN
  3328621  Farmworker Main Number Telephony EP             NaN

                   Activity Name Activity Start Timestamp Queue Name Agent Name  \
  207                        NaN   2025/01/12 02:07:52 PM        NaN        NaN
  208      LanguageSelectionMenu   2025/01/12 02:07:52 PM        NaN        NaN
  209                        NaN   2025/01/12 02:07:53 PM        NaN        NaN
  210         FarmworkerMainMenu   2025/01/12 02:08:00 PM        NaN        NaN
  211                        NaN   2025/01/12 02:12:58 PM        NaN        NaN
  ...                        ...                      ...        ...        ...
  3328617  LanguageSelectionMenu   2025/03/29 08:06:42 PM        NaN        NaN
  3328618                    NaN   2025/03/29 08:06:42 PM        NaN        NaN
  3328619     FarmworkerMainMenu   2025/03/29 08:06:49 PM        NaN        NaN
  3328620                    NaN   2025/03/29 08:27:37 PM        NaN        NaN
  3328621                    NaN   2025/03/29 08:35:26 PM        NaN        NaN

          Termination Reason
  207                    NaN
  208                    NaN
  209                    NaN
  210                    NaN
  211                    NaN
  ...                    ...
  3328617                NaN
  3328618                NaN
  3328619                NaN
  3328620      Customer Left
  3328621      Customer Left

  [48200 rows x 8 columns]},
 'SetCallerID': {'ids': 15        0004529f-0f07-421c-9d72-4baed1a8559e
  16        0004ac0b-e969-4444-ad9e-68f540580a5b
  36        000a3bc0-45e5-49e5-8bda-3f2141b2bc38
  66        001232d0-25a9-4b83-9215-fc053d8077d3
  84        001853bf-3199-412f-8c71-e6c29ba451ce
                            ...
  248378    ffeeeb2b-2388-4171-ad94-8579d212788e
  248391    fff2d0b9-dafc-4d9e-952a-51b8a30cc4c0
  248411    fff67ad3-7935-42db-9e3f-bd8c7d6de5ee
  248423    fff98171-31fb-4c91-af7e-9b4676e1c413
  248424    fffa0b4e-59dc-4b77-b4eb-42b83390acbb
  Name: Contact Session ID, Length: 9358, dtype: object,

In [ ]:
# verify the shape matches Krish's analysis
for cat in last_act:
    print(cat, ":", len(results[cat]["ids"]))

LanguageSelectionMenu : 27545
ClinicVoicemailTransfer : 25721
MainMenu : 13075
DisconnectContact1 : 12010
LegalMenu2 : 11987
FarmworkerMainMenu : 9640
SetCallerID : 9358
LegalServerScreenPop : 8910
FrontDeskTransfer1 : 7890
ClosedMenu : 7765
FrontDeskTransfer2 : 6895
OtherLegalMenu : 6863
StaffDirectorySpanishTransfer : 3959
FrontDeskTransfer : 2545
TenantMenu : 2394
CriminalRecordsVoicemailTransfer : 2267
OtherLegalOtherMenu : 2136
DivorceOrParentingMenu : 1462
QueueMenu1 : 1287
LegalMenu1 : 1267
SeniorsMenu : 1209
TenantDeterrenceMenu : 870
HousingMenu : 837
HIVVoicemailTransfer : 836
PlayMOH300s : 785
HIVMenu : 771
ScreenPopProcessComplete : 694
AddressFaxHoursMenu : 672
PreTenantMenu : 604
FamilyMenu : 543
FrontDeskTransfer3 : 541
ChildSupportMenu : 540
ImmigrationMenu : 527
SeniorsADAPTMenu : 502
OtherLegalPersonalInjuryMenu : 479
OtherLegalCriminalCaseMenu : 454
SuburbsOrCityMenu : 444
SuburbanSeniorsMenu : 442
TransferToSafeHaven : 412
SimpleDivorceMenu : 353
BenefitsMenu : 298
SubSeniorPreQueueMessage1_1 : 278
ThankYouGoodbye : 228
IntakePreQueueMessage1 : 219
SeniorsConfirmationMenu : 212
VeteransBenefitsVoicemailTransfer : 185
EmploymentMenu : 183
No activity : 0
DisconnectContact2 : 158
TraffickingVoicemailTransfer : 139
AppointmentMenu : 138
SeniorNotCookCoMenu : 127
ImmigrationOtherMenu : 116
HolidayPrompt : 85
DisconnectCallbackContact : 64
MigrantVoicemailTransfer : 67
ComplimentOrComplaintMenu : 58
PreQueueMessage2 : 37
HelpWithLegalorOtherReasonMenu : 34
DisconnectContact : 32
WorkersCompMenu : 31
GetLoggedInSubSeniorTenantAgents : 27
ReadANI : 27
PlayErrorMessage : 22
CallbackRetry : 48
GetLoggedInSubSeniorOtherAgents : 8
CollectCallbackNumber : 5
ConfirmCallbackNumber : 4
SubSeniorPreQueueMessage1_2 : 4
GetLoggedInSubSeniorOtherSPAgents : 2
SubSeniorOtherQueue : 2
GetLoggedInConsumerAgents : 1
ImmigrationSPQueue : 1
GetLoggedInOtherSubSeniorsAgents : 1
SubSeniorTenantQueue : 1
EducationSPQueue : 1
PlayCCBConfirmation : 1
SubSeniorHomeownerQueue : 1
SubSeniorConsumerQueue : 1
GetLoggedInSubSeniorTenantSPAgents : 1

In [94]:
results['MainMenu']['journeys'].head(20)

,Contact Session ID,EP Name,Flow Name,Activity Name,Activity Start Timestamp,Queue Name,Agent Name,Termination Reason
399,01936273-982f-4586-8e52-bc72636a719d,NaN,LACMain,NaN,2025/01/15 03:13:15 PM,NaN,NaN,NaN
400,01936273-982f-4586-8e52-bc72636a719d,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/01/15 03:13:15 PM,NaN,NaN,NaN
401,01936273-982f-4586-8e52-bc72636a719d,Main Number Telephony EP,LACMain,NaN,2025/01/15 03:13:15 PM,NaN,NaN,NaN
402,01936273-982f-4586-8e52-bc72636a719d,Main Number Telephony EP,NaN,MainMenu,2025/01/15 03:13:26 PM,NaN,NaN,NaN
403,01936273-982f-4586-8e52-bc72636a719d,Main Number Telephony EP,NaN,NaN,2025/01/15 03:14:03 PM,NaN,NaN,NaN
504,028c8e92-3f67-42ee-abdc-5786324f100b,NaN,LACMain,NaN,2025/01/15 11:59:44 AM,NaN,NaN,NaN
505,028c8e92-3f67-42ee-abdc-5786324f100b,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/01/15 11:59:44 AM,NaN,NaN,NaN
506,028c8e92-3f67-42ee-abdc-5786324f100b,Main Number Telephony EP,LACMain,NaN,2025/01/15 11:59:44 AM,NaN,NaN,NaN
507,028c8e92-3f67-42ee-abdc-5786324f100b,Main Number Telephony EP,NaN,MainMenu,2025/01/15 11:59:54 AM,NaN,NaN,NaN
508,028c8e92-3f67-42ee-abdc-5786324f100b,Main Number Telephony EP,NaN,NaN,2025/01/15 12:00:29 PM,NaN,NaN,NaN
914,04283b08-9a01-4543-b7c4-c10e3a3412f1,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/01/15 08:56:52 AM,NaN,NaN,NaN
915,04283b08-9a01-4543-b7c4-c10e3a3412f1,Main Number Telephony EP,LACMain,NaN,2025/01/15 08:56:52 AM,NaN,NaN,NaN
916,04283b08-9a01-4543-b7c4-c10e3a3412f1,Main Number Telephony EP,NaN,MainMenu,2025/01/15 08:56:59 AM,NaN,NaN,NaN
917,04283b08-9a01-4543-b7c4-c10e3a3412f1,Main Number Telephony EP,NaN,MainMenu,2025/01/15 08:57:31 AM,NaN,NaN,NaN
918,04283b08-9a01-4543-b7c4-c10e3a3412f1,Main Number Telephony EP,NaN,NaN,2025/01/15 08:57:31 AM,NaN,NaN,NaN
973,04a3bea0-4134-4761-bba2-8cad92377f6c,NaN,LACMain,NaN,2025/01/13 12:06:38 PM,NaN,NaN,NaN
974,04a3bea0-4134-4761-bba2-8cad92377f6c,Main Number Telephony EP,NaN,LanguageSelectionMenu,2025/01/13 12:06:38 PM,NaN,NaN,NaN
975,04a3bea0-4134-4761-bba2-8cad92377f6c,Main Number Telephony EP,LACMain,NaN,2025/01/13 12:06:38 PM,NaN,NaN,NaN
976,04a3bea0-4134-4761-bba2-8cad92377f6c,Main Number Telephony EP,NaN,MainMenu,2025/01/13 12:06:49 PM,NaN,NaN,NaN
977,04a3bea0-4134-4761-bba2-8cad92377f6c,Main Number Telephony EP,NaN,NaN,2025/01/13 12:07:08 PM,NaN,NaN,NaN